select *from batch321
update batch321 set address='JAMMULAPALEM' where SNO=3
DROP TABLE batch321
ROLLBACK
DESC CUSTOMERS
INSERT INTO CUSTOMERS VALUES ('RAMESH','PEDDANA','TAMIL',23.45,87.643,'KOLIMIKADAPALLI','BAPATLA')
ALTER TABLE CUSTOMERS DROP UNUSED COLUMNS
SELECT * FROM BATCH321
ALTER TABLE customers RENAME COLUMN CUS_SAL TO cust_sal;
SELECT *FROM CUSTOMERS
ALTER TABLE CUSTOMERS DROP COLUMN VILLAGE
ROLLBACK;
DELETE FROM CUSTOMERS WHERE COLUMN CUS_BAL=54.421;